name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        working-directory: task-manager

      - name: Lint
        run: npx nx lint api
        working-directory: task-manager

      - name: Test
        run: npm test
        working-directory: task-manager

      - name: Build
        run: npm run build
        working-directory: task-manager

      - name: Docker build
        run: docker build -t task-manager-api:ci -f Dockerfile .
        working-directory: task-manager
